# Generated by Django 2.1.2 on 2018-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipoViv', models.CharField(max_length=100)),
            ],
        ),
    ]
