# Generated by Django 2.1.2 on 2018-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20181030_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(default='con1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='{% static /images %}'),
        ),
    ]
